/**
 * Utility to parse SVG strings generated by Gemini into ShadowCanvas elements.
 */

import { v4 as uuidv4 } from 'uuid';

/**
 * Extracts a numeric attribute from an element, falling back to 0.
 */
const getNum = (el, attr, fallback = 0) => {
    const val = el.getAttribute(attr);
    if (val === null) return fallback;
    const parsed = parseFloat(val);
    return isNaN(parsed) ? fallback : parsed;
};

/**
 * Parses an SVG string into an array of canvas elements.
 * Supported elements: rect, circle, line, text
 *
 * @param {string} svgString - The raw SVG string from Gemini
 * @returns {Array<Object>} Array of canvas elements
 */
export const parseSvgToCanvasElements = (svgString) => {
    if (!svgString || typeof svgString !== 'string') {
        console.warn('SVG Parser: Invalid SVG string provided');
        return [];
    }

    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, "image/svg+xml");
    
    // Check for parsing errors
    const parseError = doc.querySelector('parsererror');
    if (parseError) {
        console.error('SVG Parser: Failed to parse SVG', parseError.textContent);
        return [];
    }

    const canvasElements = [];
    const svgElement = doc.querySelector('svg');

    if (!svgElement) {
        console.warn('SVG Parser: No <svg> element found in the parsed document.');
        return [];
    }

    // Iterate through all children of the SVG element
    for (const child of svgElement.children) {
        const type = child.tagName.toLowerCase();
        
        try {
            switch (type) {
                case 'rect': {
                    const x = getNum(child, 'x');
                    const y = getNum(child, 'y');
                    const width = getNum(child, 'width');
                    const height = getNum(child, 'height');
                    
                    canvasElements.push({
                        id: uuidv4(),
                        type: 'rect',
                        x,
                        y,
                        width,
                        height,
                        strokeColor: child.getAttribute('stroke') || '#1a103d',
                        fillColor: child.getAttribute('fill') || 'none',
                        strokeWidth: getNum(child, 'stroke-width', 2)
                    });
                    break;
                }
                
                case 'circle': {
                    const cx = getNum(child, 'cx');
                    const cy = getNum(child, 'cy');
                    const r = getNum(child, 'r');
                    
                    canvasElements.push({
                        id: uuidv4(),
                        type: 'circle',
                        x: cx - r, // Convert center to top-left bounding box
                        y: cy - r,
                        width: r * 2,
                        height: r * 2,
                        strokeColor: child.getAttribute('stroke') || '#1a103d',
                        fillColor: child.getAttribute('fill') || 'none',
                        strokeWidth: getNum(child, 'stroke-width', 2)
                    });
                    break;
                }
                
                case 'line': {
                    const x1 = getNum(child, 'x1');
                    const y1 = getNum(child, 'y1');
                    const x2 = getNum(child, 'x2');
                    const y2 = getNum(child, 'y2');
                    
                    canvasElements.push({
                        id: uuidv4(),
                        type: 'line',
                        x: Math.min(x1, x2), // Bounding box x
                        y: Math.min(y1, y2), // Bounding box y
                        width: Math.abs(x2 - x1) || 1, // Avoid 0 width
                        height: Math.abs(y2 - y1) || 1,
                        x1,
                        y1,
                        x2,
                        y2,
                        strokeColor: child.getAttribute('stroke') || '#1a103d',
                        strokeWidth: getNum(child, 'stroke-width', 2)
                    });
                    break;
                }
                
                case 'text': {
                    const x = getNum(child, 'x');
                    const y = getNum(child, 'y');
                    const text = child.textContent || '';
                    
                    // Simple estimation of bounds for text since we can't measure rendering here easily
                    const fontSize = getNum(child, 'font-size', 16);
                    
                    canvasElements.push({
                        id: uuidv4(),
                        type: 'text',
                        x,
                        y,
                        width: text.length * (fontSize * 0.6), // Rough estimate
                        height: fontSize * 1.2,
                        text,
                        fontSize,
                        fontFamily: child.getAttribute('font-family') || 'normal',
                        strokeColor: child.getAttribute('fill') || '#1a103d' // Use fill color for text in canvas usually
                    });
                    break;
                }
                
                default:
                    console.log(`SVG Parser: Ignoring unsupported element type <${type}>`);
                    break;
            }
        } catch (e) {
            console.warn(`SVG Parser: Error parsing <${type}> element`, e);
        }
    }

    return canvasElements;
};
